// types.js
const UPDATE_CELL = 'UPDATE_CELL';
const NEW_BOARD = 'NEW_BOARD';
const RESET_BOARD = 'RESET_BOARD';
const BACKTRACK_BOARD = 'BACKTRACK_BOARD';
const SOLVE_INSTANTLY = 'SOLVE_INSTANTLY';
const VALIDATE_SOLUTION = 'VALIDATE_SOLUTION';
const UNDO_MOVE = 'UNDO_MOVE';
const BACKTRACK_SPEED = 'BACKTRACK_SPEED';
const DIFFICULTIES_CHANGE = 'DIFFICULTIES_CHANGE';
const HOW_AM_I_DOING = 'HOW_AM_I_DOING';

export default {
  UPDATE_CELL,
  NEW_BOARD,
  RESET_BOARD,
  BACKTRACK_BOARD,
  SOLVE_INSTANTLY,
  VALIDATE_SOLUTION,
  UNDO_MOVE,
  BACKTRACK_SPEED,
  DIFFICULTIES_CHANGE,
  HOW_AM_I_DOING
};
