// types.js
const UPDATE_CELL = 'UPDATE_CELL';
const NEW_BOARD = 'NEW_BOARD';
const RESET_BOARD = 'RESET_BOARD';
const BACKTRACK_BOARD = 'BACKTRACK_BOARD';
export default {
  UPDATE_CELL,
  NEW_BOARD,
  RESET_BOARD,
  BACKTRACK_BOARD
};
