// types.js
const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';
const UPDATE_NAME = 'UPDATE_NAME';
const UPDATE_CELL = 'UPDATE_CELL';
const NEW_BOARD = 'NEW_BOARD';

export default {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  UPDATE_NAME,
  UPDATE_CELL,
  NEW_BOARD
};
