// types.js
const UPDATE_CELL = 'UPDATE_CELL';
const NEW_BOARD = 'NEW_BOARD';
const RESET_BOARD = 'RESET_BOARD';
const BACKTRACK_BOARD = 'BACKTRACK_BOARD';
const SOLVE_INSTANTLY = 'SOLVE_INSTANTLY';
const VALIDATE_SOLUTION = 'VALIDATE_SOLUTION';
const UNDO_MOVE = 'UNDO_MOVE';

export default {
  UPDATE_CELL,
  NEW_BOARD,
  RESET_BOARD,
  BACKTRACK_BOARD,
  SOLVE_INSTANTLY,
  VALIDATE_SOLUTION,
  UNDO_MOVE
};
